version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    image: docker_api:latest
    ports:
      - 10355:10355
    runtime: nvidia
    command: python3.11 main.py

  view:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    image: docker_view:latest
    volumes:
      - ../../default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 10356:80
    command: /bin/bash -c "nginx -g 'daemon off;'"
